In [25]:
# --import(s) ----------
import numpy as np

# -- Contents 2 Cover --
# Linear Algebra
# Matrices and Vectors
# The NumPy Library
# Solving Linear Equations
# Python Examples

# Matrixs are defined by Rows x Columns

a = [1, 3, 7, 2]

print('print(a)')
print(a)
print("")

A = [ [1 , 3 ,  7 ,  2]
     ,[5 , 8 , -9 ,  0]
     ,[6 ,-7 , 11 , 12]]

print('print(A)')
print(A)
print()

a = np.array([ [1]
              ,[3]
              ,[7]
              ,[2] ])

print('print("a = ", a)')
print("a = ", a)
print()

A = np.matrix([ [1 ,  3 ,  7 ,  2]
               ,[5 ,  8 , -9 ,  0]
               ,[6 , -7 , 11 , 12] ])

print("print('A = ', A)")
print("A = ", A)
print()


print(a)
[1, 3, 7, 2]

print(A)
[[1, 3, 7, 2], [5, 8, -9, 0], [6, -7, 11, 12]]

print("a = ", a)
a =  [[1]
 [3]
 [7]
 [2]]

print('A = ', A)
A =  [[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]



In [26]:
# IMPORTANT: notice the multiplication result, it's different that using an array ... THIS IS CORRECT FOR MATRIX MULTIPLICATION
A = np.matrix([ [ 0 ,  1]
               ,[-2 , -3] ])

B = np.matrix([ [1 ,  0]
               ,[3 , -2] ])

C = A + B
print("A + B = ", C)

C = A - B
print("A - B = ", C)

C = A * B
print("A * B = ", C)

A + B =  [[ 1  1]
 [ 1 -5]]
A - B =  [[-1  1]
 [-5 -1]]
A * B =  [[  3  -2]
 [-11   6]]


In [27]:
# IMPORTANT: notice the multiplication result, it's different that using a matrix ... THIS IS INCORRECT FOR MATRIX MULTIPLICATION
A = np.array([ [ 0 ,  1]
              ,[-2 , -3] ])

B = np.array([ [1 ,  0]
              ,[3 , -2] ])

C = A + B
print("A + B = ", C)

C = A - B
print("A - B = ", C)

# NOTE: this DOES NOT WORK, it performs elementwise multiplication
C = A * B 
print("A * B = ", C)

A + B =  [[ 1  1]
 [ 1 -5]]
A - B =  [[-1  1]
 [-5 -1]]
A * B =  [[ 0  0]
 [-6  6]]


In [28]:
# NOTE: Working Alternatives, using array vs matrix
A = np.array([ [ 0 ,  1]
              ,[-2 , -3] ])

B = np.array([ [1 ,  0]
              ,[3 , -2] ])

C = A.dot(B)
print("A.dot(B) = ", C)

C = np.dot(A, B) 
print("np.dot(A, B) = ", C)

# IMPORTANT: this option was depreciated and np.mat was removed in NumPy 2.0 release
#C = np.mat(A) * np.mat(B) 
#print("np.mat(A) * np.mat(B) = ", C)

C = np.asmatrix(A) * np.asmatrix(B) 
print("np.asmatrix(A) * np.asmatrix(B) = ", C)

C = np.matmul(A, B) 
print("np.matmul(A, B) = ", C)

A.dot(B) =  [[  3  -2]
 [-11   6]]
np.dot(A, B) =  [[  3  -2]
 [-11   6]]
np.asmatrix(A) * np.asmatrix(B) =  [[  3  -2]
 [-11   6]]
np.matmul(A, B) =  [[  3  -2]
 [-11   6]]


In [29]:
A = np. array([ [1, 3, 7, 2]
               ,[5, 8, -9, 0]
               ,[6, -7, 11, 12]])

print("A = "); print(A)

atr = np.transpose(A)

print()
print("Transpose of A = "); print(atr)

B = np.array([ [1, 5]
              ,[4, 5]
              ,[3, 2]
              ,[7, 8]])

print()
print("B = "); print(B)

btr = np.transpose(B)

print()
print("Transpose of B = "); print(btr)


A = 
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]

Transpose of A = 
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]

B = 
[[1 5]
 [4 5]
 [3 2]
 [7 8]]

Transpose of B = 
[[1 4 3 7]
 [5 5 2 8]]


In [30]:
# Createing a little dataset
hours_studied = np.array([1, 2, 2, 3, 4, 5, 6, 7], dtype = float)
practice_tests = np.array([0, 1, 2, 1, 2, 3, 3, 4], dtype = float)
exam_score = np.array([50, 55, 58, 63, 68, 75, 79, 85], dtype = float)

In [31]:
y = exam_score
x = np.column_stack([hours_studied, practice_tests])
print(x.shape)
print(y.shape)

(8, 2)
(8,)


In [32]:
a = x[0] # the 1st student [hours_studied, practice_tests]
a

array([1., 0.])

In [33]:
a_length = np.linalg.norm(a)
print('length of a', a_length)

length of a 1.0


In [34]:
b = x[4] # the 5th student [hours_studied, practice_tests]
print(b)

[4. 2.]


In [35]:
dot_ab = np.dot(a, b)
print(dot_ab)

4.0


In [36]:
cos_sin = dot_ab/(np.linalg.norm(a) * np.linalg.norm(b))
print(cos_sin)

0.8944271909999159
